### ISSUE TITLE
sequential simulations

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSimulations.jl#109]
Enable simulations of sequential problems. Essentially, update #23 for refactor.

**Comment by jd-lara** [comment]
The current implementation of the UC problem won't allow having sequential updates of the duration constraints. 

See here

https://github.com/NREL/PowerSimulations.jl/blob/f301c43937de0a36772dcbc766f4898eefbfb0fa/src/devices/device_models/common/duration_constraints.jl#L20

This code uses the initial value to decide how the number of steps that *looks back* but it is not used to generate an affine expression of variables and the initial condition.
