### ISSUE TITLE
EconomicDispatch under GLPK rejects interval constraints with equal bounds

### ISSUE THREAD

**Issue by bwbush** [NREL/PowerSimulations.jl#135]
`EconomicDispatch` using GLPK rejects interval constraints where the lower and upper bound are identical, but his occurs for some of the PV and hydro in RTS-GMLC.  These should probably automatically be converted to equality constraints.

See https://github.nrel.gov/SIIP/dr-study-1/issues/4 for an example.

**Comment by jd-lara** [comment]
Thanks, I will create a case for this that goes into an equality constraint instead.

**Comment by jd-lara** [comment]
@bwbush I have been looking into this issue and it a variable has equal bounds it should be fixed. There seems to be something wrong in the formulation. Can you please add the example here? I can't easily access the content in the internal repo.
