### ISSUE TITLE
Model Auto Rebuild when Features are updated that preserves model Type

### ISSUE THREAD

**Issue by dsigler1234** [NREL/PowerSimulations.jl#141]
If we use PowerSystems to create a System as follows

rts_sys = PSY.System(rts_dict)

then build the model as follows by creating and passing a StructuredModel

mid_model_1 = StructuredModel(parent=root_model, id=1, num_scenarios=nbranch, prob=0.5)
rts_ed_cp = PSI.EconomicDispatch(deepcopy(rts_sys), PSI.CopperPlatePowerModel; optimizer=the_optimizer, parameters=false, JuMPmodel=mid_model_1)

and then make a modification to the model to eliminate mingen

rts_ed_cp.devices[:ThermalGenerators] = PSI.DeviceModel(ThermalGen, PSI.ThermalDispatchNoMin)

the model must be rebuilt to reflect this modification using something like 

PSI.build_op_model!(rts_ed_cp; optimizer = the_optimizer, parameters=false).

 It would be nice if the model just auto rebuilt once the updates to the devices were made. Also the solution I have shown here causes a problem when one has passed in a StructuredModel to the PSI.EconomicDispatch function because 

PSI.build_op_model!(rts_ed_cp; optimizer = the_optimizer, parameters=false) 
builds the model from scratch and the result is that rts_ed_cp is no longer a StructuredModel but just a regular JuMP model. Somehow there needs to be a way to start with StructuredModel build it, make modifications to it, rebuild it, and have the end model still be a StructuredModel.

**Comment by jd-lara** [comment]
The code has changed and this is no longer an issue.
