### ISSUE TITLE
ParameterJuMP.Parameter vs. ParameterJuMP.ParameterRef

### ISSUE THREAD

**Issue by dsigler1234** [NREL/PowerSimulations.jl#142]
To construct a Julia env that utilized StructJuMP, JuMP, ParameterJuMP with PowerSimulations.jl I needed to use

StructJuMP#master
JuMP#master
ParameterJuMP#master

and I needed to replace ParameterJuMP.Parameter with ParameterJuMP.ParameterRef everywhere in my local version of PowerSimulations.jl.

**Comment by jd-lara** [comment]
This issue was solved in #139 by pinning the version of ParameterJuMP.
