### ISSUE TITLE
Some NESTA models solve with PowerModels, but not PowerSimulations

### ISSUE THREAD

**Issue by bwbush** [NREL/PowerSimulations.jl#144]
I'm not sure if this is of interest, but I noticed that several of the NESTA models solve with `PowerModels.jl` but not with `PowerSimulations.jl`.

The `Status` column in [nesta-dynamic.tsv](https://github.com/NREL/tda-ps/blob/0de400c74e01ce2da03c51148809e9e79e3fae51/simulations/nesta-dynamic.tsv) lists which models are infeasible under `PowerSimulations.jl`.  Compare this to the `PowerModel.jl` results in [nesta-static.tsv](https://github.com/NREL/tda-ps/blob/0de400c74e01ce2da03c51148809e9e79e3fae51/simulations/nesta-static.tsv) which indicate that the same models have feasible solutions.

The scripts [nesta-static.jl](https://github.com/NREL/tda-ps/blob/0de400c74e01ce2da03c51148809e9e79e3fae51/simulations/nesta-static.jl) and [nesta-dynamic.jl](https://github.com/NREL/tda-ps/blob/0de400c74e01ce2da03c51148809e9e79e3fae51/simulations/nesta-dynamic.jl) generate the aforementioned tables.  Log files from the runs are archived in [the same folder](https://github.com/NREL/tda-ps/tree/0de400c74e01ce2da03c51148809e9e79e3fae51/simulations).

**Comment by jd-lara** [comment]
This is a really good contribution, thanks a lot

**Comment by bwbush** [comment]
FYI: We've moved this repository of contingency cases to https://github.com/NREL/tda-ps/.

**Comment by bwbush** [comment]
With interruptible loads, the NESTA models have more problems.  See https://github.com/NREL/tda-ps/blob/master/contingency-datasets/shedding/ReadMe.md.

**Comment by jd-lara** [comment]
@bwbush when trying to figure out why a linear model doesn't solve this might be useful 
https://github.com/NREL/PowerSimulations.jl/issues/129#issuecomment-494590145

**Comment by jd-lara** [comment]
@bwbush the new master should have resolved this.

**Comment by jd-lara** [comment]
Closed via #320. We can test again but the repository is no longer available.
