### ISSUE TITLE
Interruptible load is missing `econ`

### ISSUE THREAD

**Issue by bwbush** [NREL/PowerSimulations.jl#152]
For interruptible loads, PowerSimulations looks for an `econ` field to add to the cost function, https://github.com/NREL/PowerSimulations.jl/blob/8151bbcd7e10e3755120c0bd074b76b5715b8fcc/src/devices/device_models/common/cost_functions.jl#L72, but PowerSystems has a `sheddingcost::Float64 # $/MWh` field instead, https://github.com/NREL/PowerSystems.jl/blob/570c5d08a20241216a3789a76f209b1d9520ce93/src/models/loads/controllable_loads.jl#L10 .

**Comment by jd-lara** [comment]
This should be opened also in PowerSystems. Since we haven't created a proper collection of demand response loads then this is largely untested in both packages.

**Comment by bwbush** [comment]
I understand the situation better.  It looks like PowerSimulations is correct, but PowerSystems in missing the `econ` field for `InterruptibleLoad`.

**Comment by bwbush** [comment]
I created https://github.com/NREL/PowerSystems.jl/issues/244.  You may want to close this issue

**Comment by jd-lara** [comment]
I will keep it open since as per #134 interruptible loads testing is still needed.

**Comment by bwbush** [comment]
Here is the workaround I created: https://github.com/bwbush/PowerSimulations.jl/commit/accd67c773f4075a9d5f0f6dbe938e2f429b784a .

Load shedding seems to work for me now.

**Comment by jd-lara** [comment]
Ok, thanks I will make a PR to PowerSystems to address it. If you have already structures for DR we can integrate them
