### ISSUE TITLE
PWL not compatible with NoMinThermal

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSimulations.jl#156]

**Comment by sourabhdalvi** [comment]
The PWL binding constraints is causing  the model to be infeasible. This constraint forces the model Dispatch variable `Pth` to be equal to sum of `Pth_pwl_x`.
`c = JuMP.@constraint(ps_m.JuMPmodel, variable == sum([pwlvars[ix] for (ix, pwlvar) in enumerate(pwlvars)]) )`
But the issue arises as the  `Pth_pwl_i` variables are bounded with in the range 
`0 - (cost_comp[i+1][2] - cost_comp[i][2])`.
We were missing out the  `(0-cost_comp[1][2])` so the unit will never be able to operate at its max capacity but only in the `range (0,Max-Min)`
Also the behavior of this  `(0-cost_comp[1][2])`  component will change depending on the type of formulation (for UC and ED it should be triggered by the commitment variable/parameter acting more like a no-load cost)  but in the ThermalDispatchNoMin we need a `Pth_pwl_0` variable.
I have created a PR to tackle all of the issue.
