### ISSUE TITLE
Why are results in the results_dataframe rounded to so few digits?

### ISSUE THREAD

**Issue by bwbush** [NREL/PowerSimulations.jl#164]
The results dataframe is the easiest access to to the optimization results, but the values are rounded to just two digits, making it useless for some analytic purposes: https://github.com/NREL/PowerSimulations.jl/blob/f82822e706fcaa079b6830ff088da3cb80ea0253/src/routines/get_results.jl#L1.

**Comment by jd-lara** [comment]
This can be fixed quickly. I will make a PR

**Comment by jd-lara** [comment]
The answer to the question is that the code for the results storage was a mix of getting results and better printing.
