### ISSUE TITLE
dc lines not included in StandardPTDFForm

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSimulations.jl#187]
[this line](https://github.com/NREL/PowerSimulations.jl/blob/jd/sim_update/src/network/network_constructor.jl#L19) filters to just `ACBranches` and the `DCBranches` never get handled.

**Comment by jd-lara** [comment]
This is the correct behaviour. DC branches are modeled separately as injections and withdrawals from the arcs.
