### ISSUE TITLE
fix tests

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSimulations.jl#189]
- [x] thermal gen (data) @jd-lara 
 - [x] renewable gen @jd-lara 
 - [x] load @jd-lara 
 - [x] storage @sourabhdalvi 
 - [x] hydro  @sourabhdalvi 
 - [x] network @claytonpbarrows 
 - [x] operation constructor @claytonpbarrows
 - [x] operation solve @claytonpbarrows

**Comment by jd-lara** [comment]
operation solves also requires some proper test data such as some UC cases with known results.
