### ISSUE TITLE
Unable to create an EconomicDispatch model with a PowerSystem struct that has no thermal generators

### ISSUE THREAD

**Issue by jmaack24** [NREL/PowerSimulations.jl#191]
Attempting to create an EconomicDispatch model when using a PowerSystem struct with no thermal generators results in the error
```
MethodError: no method matching activepower_variables(::PowerSimulations.CanonicalModel, ::Nothing, ::UnitRange{Int64})
```

**Comment by jd-lara** [comment]
Is this is in master?.

**Comment by jmaack24** [comment]
It is.  Not sure if things have changed so this isn't an issue.

**Comment by jd-lara** [comment]
Ok, I will take a look

**Comment by jd-lara** [comment]
This should be fixed for v0.2.0. Try the branch `jd/sim_update` there is a test now that should work.

**Comment by jd-lara** [comment]
@jmaack24 this should is fixed in Master now.

**Comment by jmaack24** [comment]
Ok. I'll check it and close the issue when it works.

**Comment by jmaack24** [comment]
Confirmed this is fixed in Master.
