### ISSUE TITLE
Misleading feedforward rule check

### ISSUE THREAD

**Issue by bwbush** [NREL/PowerSimulations.jl#223]
Either the arguments of `%` in line 131 are backwards or the word `multiple` in line 133
 should instead be `divisor` or `factor`:
https://github.com/NREL/PowerSimulations.jl/blob/cdde344d74104d60cbe0aa2f76eb0298a2b80191/src/core/build_simulations.jl#L131-L135

**Comment by jd-lara** [comment]
@bwbush I will close this since the code changed to address #224
