### ISSUE TITLE
Is chronology synchronized properly?

### ISSUE THREAD

**Issue by bwbush** [NREL/PowerSimulations.jl#224]
I'm wondering if https://github.com/NREL/PowerSimulations.jl/blob/cdde344d74104d60cbe0aa2f76eb0298a2b80191/src/routines/solve_routines.jl#L91 should actually update with the `interval` of the prior stage, not the current stage?

For example, if stage one steps daily and stage two depends on stage one and steps every five minutes, then one would normally want 24 executions of stage two where the start of each of those executions differs by one hour.  However, in the current code that offset between each execution of stage two is five minutes.  The chronology checks prevent one from having stage two simulation the whole day.

**Comment by jd-lara** [comment]
This looks like an issue of semantics. Interval is defined as the time between forecast updates. Resolution defines the step-length in a forecast. 

The current implementation tries to achieve what a Day-Ahead and Real-Time dispatch do. For instance, the solution of the Day-Ahead Stage for hour 10 is used in execution number 10 of stage 2. 

Hence, your intuition is correct each execution of stage 2 has an interval of 1 hour. However, this is known from the interval property of the data not calculated directly in PowerSimulations. 

If you are finding in the example that the offset between each execution of stage two is five minutes. This means that there is a bug in the data and/or a check we need to add to catch discrepancies.

**Comment by bwbush** [comment]
That is precisely the problem I see.  Here is a listing of the output directories when I request 2 steps with 1 execution of stage one with a 48-hour horizon and 24-hour step and with 12 executions of stage two with a 5-minute step:
```
./raw_output
./raw_output/step-1-stage-1
./raw_output/step-1-stage-1/2020-04-04T00:00:00
./raw_output/step-1-stage-2
./raw_output/step-1-stage-2/2020-04-04T00:00:00
./raw_output/step-1-stage-2/2020-04-04T00:05:00
./raw_output/step-1-stage-2/2020-04-04T00:10:00
./raw_output/step-1-stage-2/2020-04-04T00:15:00
./raw_output/step-1-stage-2/2020-04-04T00:20:00
./raw_output/step-1-stage-2/2020-04-04T00:25:00
./raw_output/step-1-stage-2/2020-04-04T00:30:00
./raw_output/step-1-stage-2/2020-04-04T00:35:00
./raw_output/step-1-stage-2/2020-04-04T00:40:00
./raw_output/step-1-stage-2/2020-04-04T00:45:00
./raw_output/step-1-stage-2/2020-04-04T00:50:00
./raw_output/step-1-stage-2/2020-04-04T00:55:00
./raw_output/step-2-stage-1
./raw_output/step-2-stage-1/2020-04-05T00:00:00
./raw_output/step-2-stage-2
./raw_output/step-2-stage-2/2020-04-04T01:00:00
./raw_output/step-2-stage-2/2020-04-04T01:05:00
./raw_output/step-2-stage-2/2020-04-04T01:10:00
./raw_output/step-2-stage-2/2020-04-04T01:15:00
./raw_output/step-2-stage-2/2020-04-04T01:20:00
./raw_output/step-2-stage-2/2020-04-04T01:25:00
./raw_output/step-2-stage-2/2020-04-04T01:30:00
./raw_output/step-2-stage-2/2020-04-04T01:35:00
./raw_output/step-2-stage-2/2020-04-04T01:40:00
./raw_output/step-2-stage-2/2020-04-04T01:45:00
./raw_output/step-2-stage-2/2020-04-04T01:50:00
./raw_output/step-2-stage-2/2020-04-04T01:55:00
```
One can reproduce this with a simple modification of https://github.com/NREL-SIIP/Examples/blob/wkshp-update/RTS-GMLC%20Simulations.ipynb.

**Comment by jd-lara** [comment]
@bwbush ok here is the problem in the notebook in [55] the code
```Julia
split_forecasts!(sys_RT, 
    get_forecasts(Deterministic, sys_RT, get_forecast_initial_times(sys_RT)[1]),
    Dates.Minute(5),
    12)
``` 

Assigns 5 minute intervals, this block should be 

```Julia
split_forecasts!(sys_RT, 
    get_forecasts(Deterministic, sys_RT, get_forecast_initial_times(sys_RT)[1]),
    Dates.Hour(1),
    12)
```

**Comment by bwbush** [comment]
@jd-lara, thanks for your quick and helpful response.  This works and I was able to eliminate the workaround I had coded for it.

For reference, here is the function we're using to build the BEV demand-response study and how it deals with the various time windows and steps: https://github.nrel.gov/SIIP/dr-study-1/blob/8bac7da97ca245b29050b49e0a87bbb371e7af8f/scenarios/common.jl#L96-L212.

@claytonpbarrows might want to fix https://github.com/NREL-SIIP/Examples/blob/wkshp-update/RTS-GMLC%20Simulations.ipynb so it reflects https://github.com/NREL/PowerSimulations.jl/issues/224#issuecomment-537596238.

**Comment by jd-lara** [comment]
@bwbush I have made changes to the way that simulations are built the will break the examples. I made it possible to run several executions synchronized with an upper level stage solution.
