### ISSUE TITLE
Nodal power balance should use PowerSystems.get_forecast_value to access forecast values

### ISSUE THREAD

**Issue by jmaack24** [NREL/PowerSimulations.jl#235]
In the file electric_loads.jl in the functions _nodal_expression_fixed (both the AbstractPowerFormulation and the AbstractActivePowerFormulation versions), the time series load data is accessed using `values(PSY.get_data(forecast))`.  This returns the underlying time series data vector.

If the user changes the forecasts for the power system (for example, using `PowerSystems.split_forecasts!`), this method will not pick up the change (unless I'm misunderstanding how forecasts are implemented in PowerSystems).  It will instead grab the first `time_steps` values of the raw data.

Using `PowerSystems.get_forecast_value(forecast, t)` correctly picks up the user changes.

This issue may exist in other functions.

**Comment by jd-lara** [comment]
closed via #243
