### ISSUE TITLE
PM bus number interface broken 

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSimulations.jl#291]
Related to #115 
This line should be indexed by bus rather than 1: https://github.com/NREL/PowerSimulations.jl/blame/d62daea4585a7ac234b42c4b0538a0b177b0bc66/src/network_models/powermodels_interface.jl#L348

**Comment by jd-lara** [comment]
```canonical.variables[ps_v][name, t] = PM.var(canonical.pm_model, t, bus_number, pm_v)[bus_number]``` ?

**Comment by claytonpbarrows** [comment]
‘pm_bus’

**Comment by claytonpbarrows** [comment]
addressed in #290
