### ISSUE TITLE
Update Simulation Interface

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSimulations.jl#297]
- Remove "to_executions" from the "Synchronize" inputs and calculate base on intervals in SimulationSequence:
   - `Synchronize` currently takes `from_steps` and `to_executions` arguments. We currently don't support any use cases where `to_executions` can't be inferred from the information included in the `intervals` argument of `SimulationSequence`.

 - Remove "step_resolution" from "Simulation" arguments and calculate based on the information in SimulationSequence.

**Comment by jd-lara** [comment]
> * Remove "to_executions" from the "Synchronize" inputs and calculate base on intervals in SimulationSequence:
>   
>   * `Synchronize` currently takes `from_steps` and `to_executions` arguments. We currently don't support any use cases where `to_executions` can't be inferred from the information included in the `intervals` argument of `SimulationSequence`.

This can be fixed, currently in the works in a branch. The general approach is to infer the value of the to_executions from the data. 

> * Remove "step_resolution" from "Simulation" arguments and calculate based on the information in SimulationSequence.

This can't be eliminated if the former is also eliminated.
