### ISSUE TITLE
Variable is used when it could be nothing

### ISSUE THREAD

**Issue by daniel-thom** [NREL/PowerSimulations.jl#323]
In the code segment below from the function `build!` the check for `isnothing(stage)` should be moved directly below the assignment of `stage`.  The current code will crash if `stage` is nothing.
```
    for (stage_number, stage_name) in sim.sequence.order
        stage = get(sim.stages, stage_name, nothing)
        stage_interval = sim.sequence.intervals[stage_name]
        executions = Int(sim.step_resolution / stage_interval)
        stage.internal = StageInternal(stage_number, executions, 0, nothing)
        isnothing(stage) &&
        throw(IS.ConflictingInputsError("Stage $(stage_name) not found in the stages definitions"))
        PSY.check_forecast_consistency(stage.sys)
        _attach_feed_forward!(sim, stage_name)
    end

```

**Comment by daniel-thom** [comment]
@Lilyhanig FYI. Not sure why I can't assign it to you.

**Comment by jd-lara** [comment]
I will address this in the consecutive stage fix.

**Comment by daniel-thom** [comment]
There is a similar problem in `_check_steps` in simulation.jl.

**Comment by jd-lara** [comment]
The three functions are called after the check in build!, I will add @asserts in those.

**Comment by claytonpbarrows** [comment]
> There are similar problems in `_check_steps`, `_build_stages!`, and `_build_stage_paths!` in simulation.jl.

Should be resolved now

**Comment by claytonpbarrows** [comment]
> @Lilyhanig FYI. Not sure why I can't assign it to you.

should be resolved now
