### ISSUE TITLE
Branch flow/rate constraints repetitions

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSimulations.jl#384]
In many data sets, the value of the rate limit for branches parsed as monitored branches is, in reality, a flow constraint. Currently, we add both, this behavior can be improved to reduce the number of constraints created.

**Comment by jmaack24** [comment]
This doesn't seem like an enhancement to me.  Since the function calls are the same, the constraint references in the psi_container get overwritten and as a result the first set of constraints become inaccessible except by directly accessing the jump model.  That seems like a bug to me.

**Comment by jd-lara** [comment]
The real issue is that 2 forms of the same constraints are created. A first set is created as bounds on the variable and a second set is created as inequalities.

**Comment by jmaack24** [comment]
That's not what I'm talking about.  Here's the code fragment that I found
```
function branch_rate_constraints!(
    psi_container::PSIContainer,
    devices::IS.FlattenIteratorWrapper{B},
    model::DeviceModel{B, <:AbstractBranchFormulation},
    ::Type{<:PM.AbstractActivePowerModel},
    feedforward::Union{Nothing, AbstractAffectFeedForward},
) where {B <: PSY.ACBranch}
    constraint_data = Vector{DeviceRange}()
    for d in devices
        limit_values = (min = -1 * PSY.get_rate(d), max = PSY.get_rate(d))
        name = PSY.get_name(d)
        services_ub = Vector{Symbol}()
        for service in PSY.get_services(d)
            SR = typeof(service)
            push!(services_ub, Symbol("R$(PSY.get_name(service))_$SR"))
        end
        push!(
            constraint_data,
            DeviceRange(name, limit_values, services_ub, Vector{Symbol}()),
        )
    end
    device_range(
        psi_container,
        constraint_data,
        constraint_name(RATE_LIMIT, B),
        variable_name(FLOW_ACTIVE_POWER, B),
    )

    device_range(
        psi_container,
        constraint_data,
        constraint_name(RATE_LIMIT, B),
        variable_name(FLOW_ACTIVE_POWER, B),
    )
    return
end
```
Note that `device_range` is called twice with the same arguments.  It creates duplicate constraints.  So currently, there are 3 copies of the constraints.

**Comment by jd-lara** [comment]
Thanks for the report, I will fix this asap and tag a new version.
