### ISSUE TITLE
PM integration

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSimulations.jl#84]

**Comment by ccoffrin** [comment]
Is this PowerModels integration?  If so, what remains to be done?

**Comment by claytonpbarrows** [comment]
@ccoffrin yes. 
@jd-lara is working on:
 - Implementing the definition of the network abstract types
 - Anonymizing all the variable and constraint creation

I think those are the two things to finish the PM integration

**Comment by ccoffrin** [comment]
Ok, I am currently looking into this in PowerModels.  But if issue becomes urgent, let me know.
