### ISSUE TITLE
make DC element representations

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSimulations.jl#85]
related to #50 

 - [x] HVDC Lines
 - [ ] VSC Model of DC lines (dispatch firing angle)
 - [ ] phase shifters angle dipacth

**Comment by ccoffrin** [comment]
Just an FYI, PowerModels has support for HVDC lines similar to Matpower.  More advanced HVDC lines are implemented in, https://github.com/hakanergun/PowerModelsACDC.jl

**Comment by jd-lara** [comment]
This issue is partially resolved with #116 that closed #123.
