### ISSUE TITLE
Code continues execution after detecting errors

### ISSUE THREAD

**Issue by daniel-thom** [NREL/PowerSimulations.jl#94]
In these locations (branch=refactor-branch) errors are detected and logged, but execution continues.  This will lead to undefined and likely hard-to-debug outcomes.  Should the code throw an exception instead?

git grep -n "@error"
src/device_constructors/branch_constructor.jl:27:    isempty(PTDF) ? @error("NO PTDF matrix has been provided") : (size(PTDF.axes[1])[1] != length(ac_branches_set) ? @error("PTDF size is inconsistent") : true)
src/device_models/branches/flow_constraints.jl:18:                @error "Branch name in Array and variable do not match"
src/device_models/branches/flow_constraints.jl:49:                @error "Branch name in Array and variable do not match"
src/routines/simulation_routines.jl:5:    !(size(m[consmane]) == size(data)) ? @error("The data and the constraint are size inconsistent") : true
src/routines/solve_routines.jl:27:                @error "The model is a Mixed Integer Non-Linear Problem, please define an appropiate solver manually using the Solver= argument"
src/routines/solve_routines.jl:46:            @error "The PS Model is not a standard LP, MILP, QP, QC or NLP, please define an appropiate solver manually using the Solver argument"
src/routines/solve_routines.jl:61:        @error "Problem has no solution."
src/service_models/reserves.jl:53:    (length(time_index) != time_periods) ? @error("Length of time dimension inconsistent") : true
src/service_models/reserves.jl:66:                @error "Gen name in Array and variable do not match"
src/service_models/reserves.jl:83:                @error "Gen name in Array and variable do not match"

**Comment by daniel-thom** [comment]
@jd-lara Let me know if you agree with this proposal and I'll submit a fix.

**Comment by jd-lara** [comment]
@daniel-thom Most of these lines are still up for refactoring. However, it is good to add a proposal for how they should look like with exceptions such that they are implemented properly when we get there.
